--- 
- 
  become: true
  hosts: ansible
  tasks: 
    - 
      name: "Install python pip"
      yum: 
        name: python-pip
        state: present
    - 
      name: "Install docker-py python module"
      pip: 
        name: docker-py
        state: present
    - 
      command: "docker stop test"
      ignore_errors: true
      name: "stop the container"
    - 
      commnad: "docker rm test"
      ignore_errors: true
      name: "remove the container"
    - 
      command: "docker rmi patel244/test:0.1"
      ignore_errors: true
      name: "remove the image"
    - 
      docker_container: 
        image: "patel244/test:0.1"
        name: test
        published_ports: 
          - "0.0.0.0:8084:8080"
        state: started
      name: "Start the container"
