---
- hosts: ansible
  become: True
  tasks:
    - name: Start the container
      docker_container:
        name: test
        image: "patel244/test:0.1"
        state: started
        published_ports:
          - 0.0.0.0:8084:8080
