---
- hosts: ansible
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present 
    - name: stop the container
      command: docker stop test
      ignore_errors: yes
    - name: remove the container
      commnad: docker rm test
      ignore_errors: yes
    - name: remove the image
      command: docker rmi patel244/test:0.1
      ignore_errors: yes
    - name: Start the container
      docker_container:
        name: test
        image: "patel244/test:0.1"
        state: started
        published_ports:
          - 0.0.0.0:8084:8080
