---
- hosts: dev
  become: True
  tasks:
   - name: Install python pip
     yum:
        name: python-pip
        state: present
   - name: Install docker-py python module
     pip:
        name: docker-py
        state: present
   - name: Stop a container
     docker_container:
        name: test
        state: stopped
   - name: remove container
     docker_container:
        name: test
        state: absent
   - name: Start the container
     docker_container:
        name: test
        image: "patel244/test:0.1"
        state: started
        published_ports:
          - 0.0.0.0:8084:8080
